name: siladesbeng_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  image_picker: ^1.2.3
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  google_sign_in: ^6.2.1
  connectivity_plus: ^7.3.0
  animated_text_kit: ^4.3.0
  intl: ^0.20.3
  lottie: ^3.3.3
  shimmer: ^3.0.0
  slide_to_act: ^2.0.2
  animations: ^2.2.0
  geolocator: any
  geocoding: ^5.0.0
  fl_chart: ^1.2.0
  camera: ^0.12.0+2
  path_provider: ^2.1.6
  url_launcher: ^6.3.2
  google_mlkit_face_detection: ^0.14.0
  firebase_messaging: ^16.4.3
  flutter_local_notifications: ^22.2.0
  file_picker: 11.0.3
  qr_flutter: ^4.1.0
  share_plus: ^12.0.2
  pinput: ^6.0.2
  pdf: ^3.12.0
  flutter_svg: ^2.0.17
  showcaseview: ^5.1.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logodomain.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/banks/
    - logodomain.png
